addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"      % "1.3.5")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.11")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.3.3")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.6.1")
