addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"      % "1.4.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.12")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.6.1")
